### ISSUE TITLE
Main Menu Logo Replacement

### ISSUE THREAD

**Issue by Colmines92** [Ich73/DQM2-FanTranslation#1]
Hello, first of all I want to congratulate you for making this a reality and encouraging you to go ahead with your project and not stop.

I downloaded the project, followed the steps and it worked perfectly, and I found everything I saw very comfortable, except for the logo of the main menu, which has very low quality and the image of the key with the number was removed 2.

Current one:
![01_ich73](https://user-images.githubusercontent.com/25232329/95468233-4e415100-094c-11eb-974b-e15ec93e9e2f.png)

Original:
![03-original](https://user-images.githubusercontent.com/25232329/95468273-57322280-094c-11eb-8b9b-01bdbd3d64c2.png)

I noticed it from the first moment it came out on the screen. In the original they can put the text on top of the logos, because the text says the same: "Dragon Quest Monsters".

I don't mean to offend whoever did it, I just want the end result to be the best it can be. So I got to work trying to recreate the logo and here is the result:

![02-mine](https://user-images.githubusercontent.com/25232329/95468320-631de480-094c-11eb-829e-b01eae90be8b.png)

![screenshot](https://user-images.githubusercontent.com/25232329/95468338-66b16b80-094c-11eb-81c6-9855873b12f3.png)

I'm not saying that the one I made is perfect, but I find it a bit more enjoyable than the current one. Anyway, I am attaching the PSD file, in case you want to make any modifications, within the PSD you will find the DQ logo, Monsters logo, the key, the 2 and the texts separated in layers.

[title_up_logo.zip](https://github.com/Ich73/DQM2-FanTranslation/files/5348313/title_up_logo.zip)

If you use mine, please use the original japanese layout, just replace the image.

Another very small grammar or translation error that I found was when you break a jar and get more than one item, the dialog box shows:

Obtained 2Medical Herbs.

There had to leave a space between the quantity and item name.

Otherwise, I love the work you are doing here.

**Comment by Ich73** [comment]
#### About the translation error

> Another very small grammar or translation error [...]
> Obtained 2Medical Herbs.

I only found the text saying `Cobi receives 2Medical Herbs!` and added a space there.  
Correct me if that wasn't the text you were asking for.

-----
#### About title_up_logo

The resolution is bad because there was no plain image of the logo without the japanese text except for the image used in the banner. So that was the image I used and unfortunately it has a lower resolution than the original title_up_logo image.  
  
Your recreation of the logo looks awesome and preserving the key would be great. Thanks! I can use that to put the text below the logo. I'd have to use my version of the text so I can translate the title to several different languages.
  
Anyway changing the title_up_logo would also mean changing the banner to match the colors and the placement of the text, but I can do this.  
  
> If you use mine, please use the original japanese layout, just replace the image.

What do you mean by this? Putting the text on top of the logo instead of below the logo? Could you explain what you mean?

**Comment by Colmines92** [comment]
> I only found the text saying Cobi receives 2Medical Herbs! and added a space there.

Yes that's what I mean. Right now I don't have it in front of me and I didn't quite remember what it said.

> What do you mean by this? Putting the text on top of the logo instead of below the logo? Could you explain what you mean?

Regarding the layout, I mean that when you open the title_up_logo.arc file, inside there are two (or three, not sure) folders, one with the image (.bclim) and other(s) with the layout settings. I'm not sure if you are using the original Japanese layout. If so, then just replace the image (.bclim) and voila.

> I'd have to use my version of the text so I can translate the title to several different languages.

About the title, inside the PSD it is in editable text maintainig colors and bisel. It's up to you to use yours or mine, but I strongly recommend not to put the title texts so big that they cover the logos.
