### ISSUE TITLE
Wifi Lobby Text suggestions/problems

### ISSUE THREAD

**Issue by Clydefrosch22** [Ich73/DQM2-FanTranslation#23]
Sorry, I have no idea why github doesn't let me upload images, so imgur link again
https://imgur.com/a/6TW4mTm

**Comment by Ich73** [comment]
> Maybe there's a way to get rid of that empty line that appears?

I managed to modify the layout file such that the rankings column is thinner and the hometown column is thicker. Now all names fit and I could also keep "Hometown" instead of "Home".

> This image is untranslated.

I believe that image is transmitted when you connect to the Internet, because it is being displayed shortly after "Downloading data..." starts and I couldn't find it in the game's files. So there is no way to translate it - as with the daily Challengers GP rules.

**Comment by Ich73** [comment]
If you're using a LayeredFS patch, you can now [update your workspace](https://github.com/Ich73/DQM2-FanTranslation/wiki/Installing-LayeredFS#update-workspace) using the UW script.
