### ISSUE TITLE
The patcher just says "ERROR: the file type is mismatch"?

### ISSUE THREAD

**Issue by samcambolt270** [Ich73/DQM2-FanTranslation#4]
I can't seem to patch the game at all. I tried both with the update and without (using their respective patches) and the one _with_ the patches finishes in about 5 seconds and outputs a 7mb file called "Update 1.1 (Patches-v1.1-EN).cia". It seems to completely ignore the full game file and just patch the update file instead?
The version without the file takes much longer, but always spits out this error after "partition 1"
      ERROR: the file type is mismatch 
      ERROR: Extracting Failed
I can't figure out what I'm doing wrong.

**Comment by Ich73** [comment]
> ERROR: the file type is mismatch
> ERROR: Extracting Failed

This error occurs when Game Patcher uses [3dstool](https://github.com/dnasdw/3dstool) to extract the exefs of the ROM.
From my research the error happens if the cia file is _not decrypted_.
You can decrypt the cia file using GodMode9 (~[Decrypting a .CIA file](https://3ds.hacks.guide/godmode9-usage.html#encrypting--decrypting-a-cia-file)~) and try again.

_Edit_: As the link no longer displays the correct instructions...

> * Boot the 3DS while holding `START` to launch Godmode9
> * Navigate to the folder where your enrypted cia file is
> * Navigate to the encrypted cia file and press `A`
> * Select `"CIA image options..."`
> * Select `"Decrypt file (...)"`
> * Select `"Decrypt inplace"`
> * Press `A` to continue
> * Press `START` to reboot
> * The .cia file on your SD card is now decrypted

-----

First, note that if you want to play the updated game, you need to patch both - the base game and the update - by applying `Patches-v1.0-EN.zip` to `<base game>.cia` _and_ `Patches-v1.1-EN-zip` to `<v1.1 update>.cia`.

You should be able to patch both - the base game and the update - simultaneously by placing the following files inside a folder and running `GamePatcher.exe`.
```
<your folder>
├── <base game>.cia
├── <v1.1 update>.cia
├── Patches-v1.0-EN.zip
├── Patches-v1.1-EN.zip
└── GamePatcher.exe
```
This should give you two patched game files.
```
<your folder>
├── <base game> (Patches-v1.0-EN).cia
├── <v1.1 update> (Patches-v1.1-EN).cia
└── ...
```

-----

Alternatively you can patch the base game first...
```
<your folder>
├── <base game>.cia
├── Patches-v1.0-EN.zip
└── GamePatcher.exe
```
... and the v1.1 update afterwards.
```
<your folder>
├── <v1.1 update>.cia
├── Patches-v1.1-EN.zip
└── GamePatcher.exe
```
